# Generated by Django 5.0.6 on 2024-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_book_bookingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookingdate',
            field=models.DateTimeField(),
        ),
    ]
